# Generated by Django 3.2.4 on 2021-06-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='img',
        ),
        migrations.AddField(
            model_name='student',
            name='pref',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
